#!/usr/bin/env bash

set -eu

dna-add_cron_job() {

    ############################################################################

    if [ $# -eq 0 ]
    then
        dna-echo -e "No argument supplied for function | ${n-}${FUNCNAME[0]}${r-} |."
        dna-exit
    fi

    while getopts ":n:t:c:" arguments
    do
        case $arguments in
            n)	name="${OPTARG}"
                ;;
            t)	time="${OPTARG}"
                ;;
            c)	content="${OPTARG}"
                ;;
            \?)	dna-echo -e "Invalid option | ${n-}-${OPTARG}${r-} | for function | ${n-}${FUNCNAME[0]}${r-} |."
                dna-exit
                ;;
        esac
    done
    OPTIND=1

    if [ -z "${name-}" ]
    then
        dna-echo -e "Argument | ${n-}name [-n]${r-} | must be supplied for function | ${n-}${FUNCNAME[0]}${r-} |."
        dna-exit
    fi

    if [ -z "${time-}" ]
    then
        dna-echo -e "Argument | ${n-}time [-t]${r-} | must be supplied for function | ${n-}${FUNCNAME[0]}${r-} |."
        dna-exit
    fi

    if [ -z "${content-}" ]
    then
        dna-echo -e "Argument | ${n-}content [-c]${r-} | must be supplied for function | ${r-}${FUNCNAME[0]}${r-} |."
        dna-exit
    fi

    ############################################################################

    if [ ! -f "/usr/bin/cronic" ]
    then

        curl https://habilis.net/cronic/cronic > /usr/bin/cronic
        chmod +x /usr/bin/cronic
        echo

    fi

    ############################################################################

    dna-echo_operation -h "adding job to daily crontab via cronic"

    job_path="/etc/cron.d/${name}"
    touch "${job_path}"
    chmod 755 "${job_path}"
    echo "SHELL=/bin/bash" > "${job_path}"
    echo "PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin" >> "${job_path}"
    echo "MAILTO=${admin_mail}" >> "${job_path}"
    echo >> "${job_path}"
    echo "${time} root cronic ${content}" >> "${job_path}"

    dna-echo_operation -t

}
