#!/usr/bin/env bash

dna-apt_full_upgrade() {

    while getopts ":e" arguments; do
        case $arguments in
            e)	allow_errors="y"
                ;;
            \?)	dna-echo -m "${r-}Invalid option | ${n-}-$OPTARG${r-} | for function | ${n-}${FUNCNAME[0]}${r-} |."
                dna-exit
                ;;
        esac
    done
    OPTIND=1

    dna-echo -m "Now performing APT upgrade, dist-upgrade, and autoremove..."

    if [ "${allow_errors-null}" = "y" ]
    then
        set +e
    fi

    dna-apt_update

    dna-check_dpkg_availability

    apt-get -y upgrade
    apt-get -y dist-upgrade
    apt-get -y autoremove

    echo

    set -e

    dna-echo -m "${g-}Finished performing APT operations."

}
