#!/usr/bin/env bash

set -eu

os-apt_update {

    apt_update_stamp_path="/var/lib/apt/periodic/update-success-stamp"

    if [ -f "${apt_update_stamp_path}" ]
    then
        # Input file
        FILE="${apt_update_stamp_path}"
        # How many seconds before file is deemed "older"
        OLDTIME=6480
        # Get current and file times
        CURTIME=$(date +%s)
        FILETIME=$(stat $FILE -c %Y)
        TIMEDIFF=$(expr $CURTIME - $FILETIME)

        # Check if file older
        if [ $TIMEDIFF -gt $OLDTIME ]
        then
            echo "${b}APT cache out of date. Updating now..."
            echo
            apt-get update
            echo
        else
            echo "${g}${b}APT cache up to date."
            echo
        fi

    fi

}
