#!/usr/bin/env bash

dna-check_inception_run() {

    if [ -f $os_base_dir/inception/run-ok ]
    then
        echo "${g-}${b-}inception was previously run successfully. Continuing...${x-}"
        echo
    else
        echo "${r-}${b-}inception was NOT previously run successfully OR the system was not rebooted at the end.${x-}"
        echo
        read -p "${b-}Run it now? (Y/n): ${x-}" -n 1 -r
        echo
        if [[ ! $REPLY =~ ^[Nn]$ ]]
        then
            echo "${b-}Ok, running inception now...${x-}"
            echo
            echo "${b-}After you're done running inception and your machine automaticallty reboots, simply run the aenigma installer again.${x-}"
            echo
            sleep 3
            cd
            if [ -d "/root/inception" ]
            then
                rm -r "/root/inception"
            fi
            git clone https://github.com/openspace42/inception
            clear
            bash inception/setup
            exit
        else
            echo
            echo "${b-}No problem, you can run it [make sure you reboot this machine at the end] by executing the following commands:${x-}"
            echo
            echo "${b-} | git clone https://github.com/openspace42/inception |${x-}"
            echo
            echo "${b-} | bash inception/setup |${x-}"
            echo
            dna-exit_function
        fi
    fi

}
