#!/usr/bin/env bash

dna-check_dpkg_availability() {

    check_condition() {

        if ! fuser /var/lib/dpkg/lock &> /dev/null
        then
            condition_verified=y
        fi

    }

    dna-wait_for -d "Now waiting for other package managers to complete operations..."
    dna-echo -s "DPKG is available. Continuing..."

}
