#!/bin/bash

os-get_distro_name() {

    distro_name="$(lsb_release --id | cut -f2)"

}

os-check_distro_ubuntu() {

    ### Check that the running distro is Ubuntu

    if ! lsb_release --id | cut -f2 | grep Ubuntu >/dev/null
    then
        echo "${b}Detected distro is NOT Ubuntu. It appears instead to be:${x}"
        echo
        lsb_release -i
        echo "${b}$short_name only runs on Ubuntu.${x}"
        echo
        os-exit_function
    fi

}

os-check_distro_ubuntu_lts() {

    ### Check that the running distro is Ubuntu on an LTS version

    os-check_distro_ubuntu()

    if ! lsb_release -d | grep -q LTS
    then
        echo "${b}Detected Ubuntu version is NOT an LTS version. It appears instead to be:${x}"
        echo
        lsb_release -d
        echo "${b}$short_name only runs on Ubuntu LTS versions.${x}"
        echo
        os-exit_function
    fi

}
