#!/usr/bin/env bash

dna-check_argument_presence() {

    if [ $# -eq 0 ]
    then
        echo "${r-}${b-}No argument supplied for function | ${FUNCNAME[0]} |.${x-}"
        echo
        dna-exit_function
    fi
    
}
