#!/usr/bin/env bash

os-check_dpkg_availability() {

    echo "${b-}Now ensuring DPKG is available...${x-}"
    echo
    sleep 3
    i=0
    tput sc
    while fuser /var/lib/dpkg/lock >/dev/null 2>&1 ; do
        case $((i % 4)) in
            0 ) j="-" ;;
            1 ) j="\\" ;;
            2 ) j="|" ;;
            3 ) j="/" ;;
        esac
        tput rc
        echo -en "\\r[$j] ${b-}Waiting for other software managers to finish...${x-}"
        echo
        sleep 0.5
        ((i=i+1))
    done
    echo "${b-}DPKG available. Continuing...${x-}"
    echo

}
