#!/usr/bin/env bash

dna-get_distro_name() {

    distro_name="$(lsb_release --id | cut -f2)"

}

dna-check_distro_ubuntu() {

    ### Check that the running distro is Ubuntu

    if ! lsb_release --id | cut -f2 | grep Ubuntu >/dev/null
    then
        echo "${b-}Detected distro is NOT Ubuntu. It appears instead to be:${x-}"
        echo
        lsb_release -i
        echo "${b-}$short_name only runs on Ubuntu.${x-}"
        echo
        dna-exit_function
    fi

}

dna-check_distro_ubuntu_lts() {

    ### Check that the running distro is Ubuntu on an LTS version

    dna-check_distro_ubuntu()

    if ! lsb_release -d | grep -q LTS
    then
        echo "${b-}Detected Ubuntu version is NOT an LTS version. It appears instead to be:${x-}"
        echo
        lsb_release -d
        echo "${b-}$short_name only runs on Ubuntu LTS versions.${x-}"
        echo
        dna-exit_function
    fi

}
