#!/bin/bash

os-check_dfbs_run() {

    if [ -f $os_base_dir/dfbs/run-ok ]
    then
        echo "${g}${b}Debian First Boot Setup was previously run successfully. Continuing...${x}"
        echo
    else
        echo "${r}${b}Debian First Boot Setup was NOT previously run successfully OR the system was not rebooted at the end.${x}"
        echo
        read -p "${b}Run it now? (Y/n): ${x}" -n 1 -r
        echo
        if [[ ! $REPLY =~ ^[Nn]$ ]]
        then
            echo "${b}Ok, running DFBS now...${x}"
            echo
            echo "${b}After you're done running DFBS [make sure you reboot this machine at the end], simply run the aenigma installer again.${x}"
            echo
            sleep 3
            if [ -d "/root/Debian-First-Boot-Setup" ]
            then
                rm -r "/root/Debian-First-Boot-Setup"
            fi
            git clone https://github.com/openspace42/Debian-First-Boot-Setup
            clear
            bash Debian-First-Boot-Setup/script.sh
            exit
        else
            echo "${b}No problem, you can run it [make sure you reboot this machine at the end] by executing the following commands:${x}"
            echo
            echo "${b} | git clone https://github.com/openspace42/Debian-First-Boot-Setup |${x}"
            echo
            echo "${b} | bash Debian-First-Boot-Setup/script.sh |${x}"
            echo
            echo "${b}Exiting...${x}"
            echo
            exit
        fi
    fi

}
