#!/usr/bin/env bash

dna-check_ipv6_connectivity() {

    ############################################################################

    while getopts ":s" arguments; do
        case $arguments in
            s)	export silent="y"
                ;;
            \?)	dna-echo -e "Invalid option | ${n-}-${OPTARG}${r-} | for function | ${n-}${FUNCNAME[0]}${r-} |."
                dna-exit
                ;;
        esac
    done
    OPTIND=1

    dna-echo -m "Now testing IPv6 connectivity..."

    ipv6_ping_test_addr="2001:4860:4860::8888"

    if ping6 -q -c 1 -W 1 "${ipv6_ping_test_addr}" >/dev/null
    then
        dna-echo -s "IPv6 connectivity good."
        ipv6_available="y"
    else
        counter="4"
        ping_acquired="y"
        echo
        until ping6 -c1 "${ipv6_ping_test_addr}" &>/dev/null
        do
            dna-echo -m "Waiting ${counter} more seconds for IPv6 connectivity..."
            if [ "${counter}" = "0" ]
            then
                ping_acquired="n"
                break
            fi
            counter=$((counter - 1))
            sleep 1
        done
        if [ "${ping_acquired}" = "y" ]
        then
            dna-echo -s "IPv6 connectivity acquired."
            ipv6_available="y"
        else
            dna-echo -e "IPv6 connectivity not detected."
            ipv6_available="n"
            this_ipv6="null"
        fi
    fi
    if [ "${ipv6_available}" = "y" ]
    then
        this_ipv6="$(dig +short -6 myip.opendns.com aaaa @resolver1.ipv6-sandbox.opendns.com)"
        dna-echo -m "Your IPv6 global [public] address appears to be: | ${y-}${this_ipv6}${n-} |."
    fi

    unset silent

}
