#!/usr/bin/env bash

dna-check_ipv6_connectivity() {

    while getopts ":s" arguments; do
        case $arguments in
            s)	export silent="y"
            ;;
            \?)	echo "${r-}${b-}Invalid option | -$OPTARG | for function | ${FUNCNAME[0]} |.${x-}"
            echo
            dna-exit
            ;;
        esac
    done
    OPTIND=1

    dna-echo -m "Now testing IPv6 connectivity..."

    ipv6_ping_test_addr="2001:4860:4860::8888"

    if ping6 -q -c 1 -W 1 $ipv6_ping_test_addr >/dev/null
    then
        dna-echo -m "${g-}IPv6 connectivity good."
        ipv6_avail=y
    else
        counter=4
        ping_acquired=y
        echo
        until ping6 -c1 $ipv6_ping_test_addr &>/dev/null
        do
            dna-echo -m "Waiting $counter more seconds for IPv6 connectivity..."
            if [ $counter = 0 ]
            then
                ping_acquired=n
                break
            fi
            counter=$((counter - 1))
            sleep 1
        done
        if [ $ping_acquired = "y" ]
        then
            dna-echo -m "${g-}IPv6 connectivity acquired."
            ipv6_avail=y
        else
            dna-echo -m "${r-}IPv6 connectivity not found."
            ipv6_avail=n
        fi
    fi
    if [ $ipv6_avail = "y" ]
    then
        this_ipv6="$(dig +short -6 myip.opendns.com aaaa @resolver1.ipv6-sandbox.opendns.com)"
        dna-echo -m "${b-}Your IPv6 global [public] address appears to be: | $this_ipv6 | ${x-}"
    fi
    dna-echo -m "Finished testing IPv6 connectivity."

    unset silent

}
