#!/bin/bash

os-define_vars() {

	### Define variables. Don't change these! | No trailing slash!

	### Define these in the project itself
	### proj_name="EasyEngine-Backup-Restore"
	### short_name="ee-br"
	### author_name="nikksno"

	### Projects will be installed in this location: | /root/$proj_author/$short_name |.

	source_dir=/root/$proj_name
	base_dir=/root/$author_name
	install_dir=$base_dir/$short_name

	os_base_dir=/root/openspace42

	conf_dir=$install_dir/conf
	conf_backups_dir=$conf_dir/backups
	conf_backups_local_dir=$conf_backups_dir/local
	conf_backups_s3_dir=$conf_backups_dir/s3

	if [ ! -z "${backup_local_storage_path-}" ]
	then

		backups_archive_dir=$backup_local_storage_path/archive
		backups_latest_dir=$backup_local_storage_path/latest
		backups_temp_dir=$backup_local_storage_path/temp

	fi

	restores_dir=$install_dir/restores

	tools_dir=$install_dir/tools

	tls_dir=/etc/ssl/$short_name
	temp_dir=/tmp/$short_name

	www_dir=/var/www

}
