#!/usr/bin/env bash

dna-define_vars() {

	### Define variables [Don't change these! | No trailing slash!]

	### Projects will be installed in this location: | /root/${proj_author}/${proj_name} |.

	export source_dir="/root/${proj_name}"
	export base_dir="/root/${author_name}"
	export install_dir="${base_dir}/${proj_name}"
	export modules_dir="${install_dir}/modules"

	export os_base_dir="/root/openspace42"
	export os_conf_dir="${os_base_dir}/conf"

	export conf_dir="${install_dir}/conf"

	export conf_backups_dir="${conf_dir}/backups"
	export conf_backups_local_dir="${conf_backups_dir}/local"
	export conf_backups_s3_dir="${conf_backups_dir}/s3"

	export conf_dns_dir="${conf_dir}/dns"

	export tools_dir="${install_dir}/tools"

	export tls_dir="/etc/ssl/${proj_name}"
	export temp_dir="/tmp/${proj_name}"

	export www_dir="/var/www"

	export ssh_auth_keys_file="/root/.ssh/authorized_keys"
	export ssh_config_file="/etc/ssh/sshd_config"

}
