#!/usr/bin/env bash

dna-define_vars() {

	############################################################################

	### define variables [don't change these! | no trailing slash on paths!].
	### projects will be installed in: | /root/${proj_author}/${proj_name} |.

	############################################################################
	############################################################################

	### system.

	export tls_dir="/etc/ssl"
	export www_dir="/var/www"
	export tmp_dir="/tmp"
	export le_live_dir="/etc/letsencrypt/live"

	############################################################################

	### system ssh.

	export ssh_auth_keys_file="/root/.ssh/authorized_keys"
	export ssh_config_file="/etc/ssh/sshd_config"

	############################################################################

	### os.

	export os_base_dir="/root/openspace42"
	export os_conf_dir="${os_base_dir}/conf"

	############################################################################

	### dna.

	export dna_dir="${os_base_dir}/dna"
	export dna_version_file_path="${dna_dir}/version_installed"

	############################################################################

	### synthia

	export source_dir="/root/${proj_name}"
	export base_dir="/root/${author_name}"
	export install_dir="${base_dir}/${proj_name}"
	export modules_dir="${install_dir}/modules"

	### synthia conf

	export conf_dir="${install_dir}/conf"
	export conf_backups_dir="${conf_dir}/backups"
	export conf_backups_local_dir="${conf_backups_dir}/local"
	export conf_backups_s3_dir="${conf_backups_dir}/s3"
	export conf_dns_dir="${conf_dir}/dns"

	### synthia tools

	export tools_dir="${install_dir}/tools"

	############################################################################

	### system project-specific

	export tls_project_dir="${tls_dir}/${proj_name}"
	export tmp_project_dir="${tmp_dir}/${proj_name}"

	############################################################################
	############################################################################

}
