#!/usr/bin/env bash

dna-echo() {

    ############################################################################

    ### Do NOT use dna-exit as it depends on this.

    if [ $# -eq 0 ]
    then
        echo "${r-}${b-}No argument supplied for function | ${n-}${FUNCNAME[0]}${r-} |.${x-}"
        echo
        echo "${b-}Exiting...${x-}"
        echo
        sleep 1
        exit
    fi

    while getopts ":m:s:e:n" arguments
    do
        case $arguments in
            m)	message="${OPTARG}"
                ;;
            s)  success_message="${OPTARG}"
                ;;
            e)  error_message="${OPTARG}"
                ;;
            n)  no_newline="y"
                ;;
            \?)	echo "${r-}${b-}Invalid option | ${n-}-${OPTARG}${r-} | for function | ${n-}${FUNCNAME[0]}${r-} |.${x-}"
                echo
                echo "${b-}Exiting...${x-}"
                echo
                sleep 1
                exit
                ;;
        esac
    done
    OPTIND=1

    display_error() {

        echo "${r-}${b-}Only one message argument can be specified for function | ${n-}${FUNCNAME[0]}${r-} |.${x-}"
        echo
        echo "${b-}Exiting...${x-}"
        echo
        sleep 1
        exit

    }

    if [ -z "${no_newline-}" ]
    then
        if [ $# -gt "2" ]
        then
            display_error
        fi
    else
        if [ $# -gt "4" ]
        then
            display_error
        fi
    fi

    if [ -z "${message-}" ] && [ -z "${success_message-}" ] && [ -z "${error_message-}" ]
    then
        echo "${r-}${b-}At least one message of any type must specified for function | ${n-}${FUNCNAME[0]}${r-} |.${x-}"
        echo
        echo "${b-}Exiting...${x-}"
        echo
        sleep 1
        exit
    fi

    ############################################################################

    if [ -z "${error_message-}" ]
    then
        if [ ! "${silent-null}" = "y" ]
        then
            if [ -n "${message-}" ]
            then
                echo "${b-}${message}${x-}"
            else
                echo "${g-}${b-}${success_message}${x-}"
            fi
        fi
    else
        echo "${r-}${b-}${error_message}${x-}"
    fi

    if [ ! "${silent-null}" = "y" ] || [ -n "${error_message-}" ]
    then
        if [ -z "${no_newline-}" ]
        then
            echo
        fi
    fi

    unset message success_message error_message no_newline

}

dna-echo_operation() {

    ### evaluate arguments.

    ### ########################################################################

    if [ $# -eq 0 ]
    then
        dna-echo -e "No argument supplied for function | ${n-}${FUNCNAME[0]}${r-} |."
        dna-exit
    fi

    while getopts ":h:t" arguments
    do
        case $arguments in
            h)	echo_operation_status="head"
                export echo_operation_message="${OPTARG}"
                ;;
            t)	echo_operation_status="tail"
                ;;
            \?)	dna-echo -e "Invalid option | ${n-}-${OPTARG}${r-} | for function | ${n-}${FUNCNAME[0]}${r-} |."
                dna-exit
                ;;
        esac
    done
    OPTIND=1

    if [ -z "${echo_operation_status-}" ]
    then
        dna-echo -e "Either status flag: | ${n-}head [-h] || tail [-t]${r-} | must be supplied for function: | ${n-}${FUNCNAME[0]}${r-} |."
        dna-exit
    fi

    if [ "${echo_operation_status}" = "head" ] && [ -z "${echo_operation_message-}" ]
    then
        dna-echo -e "Variable | ${n-}operation_message${r-} | must be specified in addition to the status flag: | ${n-}head [-h]${r-} | for function: | ${n-}${FUNCNAME[0]}${r-} |."
        dna-exit
    fi

    if [ "${echo_operation_status}" = "tail" ] && [ -z "${echo_operation_message-}" ]
    then
        dna-echo -e "Variable | ${n-}operation_message${r-} | was undefined between: | ${n-}head [-h]${r-} | and now for function: | ${n-}${FUNCNAME[0]}${r-} |."
        dna-exit
    fi

    ### ########################################################################

    if [ "${echo_operation_status}" = "head" ]
    then

        dna-echo -m "Now ${echo_operation_message}..."

        unset echo_operation_status

    elif [ "${echo_operation_status}" = "tail" ]
    then

        dna-echo -s "Finished ${echo_operation_message}."

        unset echo_operation_message

    fi

}
