#!/usr/bin/env bash

dna-echo() {

    if [ $# -eq 0 ]
    then
        echo "${r-}${b-}No argument supplied for function | ${n-}${FUNCNAME[0]}${r-} |.${x-}"
        echo
        echo "${b-}Exiting...${x-}"
        echo
        sleep 1
        exit
    fi

    if [ $# -gt 2 ]
    then
        echo "${r-}${b-}Only one argument can be specified for function | ${n-}${FUNCNAME[0]}${r-} |.${x-}"
        echo
        echo "${b-}Exiting...${x-}"
        echo
        sleep 1
        exit
    fi

    while getopts ":m:s:e:" arguments; do
        case $arguments in
            m)	message="$OPTARG"
                ;;
            s)  success_message="$OPTARG"
                ;;
            e)  error_message="$OPTARG"
                ;;
            \?)	echo "${r-}${b-}Invalid option | -$OPTARG | for function | ${FUNCNAME[0]} |.${x-}"
                echo
                echo "${b-}Exiting...${x-}"
                echo
                sleep 1
                exit
                ;;
        esac
    done
    OPTIND=1

    if [ -z "${error_message-}" ]
    then
        if [ ! "${silent-null}" = "y" ]
        then
            if [ -n "${message-}" ]
            then
                echo "${b-}${message}${x-}"
            else
                echo "${g-}${b-}${success_message}${x-}"
            fi
            echo
        fi
    else
        echo "${r-}${b-}${error_message}${x-}"
        echo
    fi

    unset message success_message error_message

}
