#!/usr/bin/env bash

dna-exit() {

    if [ ! -z "${lockfile_set-}" ]
    then
        if [ -f "${lockfile_set}" ]
        then
            dna-echo -e "Exiting and clearing lockfile..."
            rm "${lockfile_set}"
        fi
    else
        dna-echo -e "Exiting..."
    fi
    sleep 1
    exit 1

}
