#!/usr/bin/env bash

dna-exit() {

    if [ ! -z "${lockfile_set-}" ]
    then
        if [ -f "${lockfile_set}" ]
        then
            dna-echo -m "${r-}Exiting and clearing lockfile..."
            rm "${lockfile_set}"
        fi
    else
        dna-echo -m "${r-}Exiting..."
    fi
    sleep 1
    exit 1

}
