#!/usr/bin/env bash

dna-exit() {

    if [ ! -z "${lockfile_set-}" ]
    then
        if [ -f "${lockfile_set}" ]
        then
            echo "${r-}${b-}Exiting and clearing lockfile...${x-}"
            echo
            rm "${lockfile_set}"
        fi
    else
        echo "${r-}${b-}Exiting...${x-}"
        echo
    fi
    sleep 1
    exit 1

}
