#!/usr/bin/env bash

dna-generate_ssh_keypair() {

    if [ $# -eq 0 ]
    then
        echo "${r-}${b-}No argument supplied for function | ${FUNCNAME[0]} |.${x-}"
        echo
        dna-exit
    fi

    while getopts ":n:" arguments; do
        case $arguments in
            n)	name="$OPTARG"
            ;;
            \?)	echo "${r-}${b-}Invalid option | -$OPTARG | for function | ${FUNCNAME[0]} |.${x-}"
            echo
            dna-exit
            ;;
        esac
    done
    OPTIND=1

    if [ -z "${name-}" ]
    then
        echo "${r-}${b-}Name | option [-n] | must be supplied for function | ${FUNCNAME[0]} |.${x-}"
        echo
        dna-exit
    fi

    ########################################################################

    echo "${b-}Now generating SSH keypair for | ${y-}${name}${x-}${b-} |...${x-}"
    echo
    ssh-keygen -t rsa -b 8192 -N "" -f "/root/.ssh/${name}"
    echo
    chmod 600 "/root/.ssh/${name}"
    ssk_keypair_privkey_path="/root/.ssh/${name}"
    ssk_keypair_pubkey_path="/root/.ssh/${name}.pub"
    echo "${b-}Finished generating SSH keypair and stored it in | ${y-}/root/.ssh/${name}[.pub]${x-}${b-} |.${x-}"
    echo

}
