#!/usr/bin/env bash

dna-get_public_ipv4() {

    ############################################################################

    while getopts ":s" arguments
    do
        case $arguments in
            s)	export silent="y"
                ;;
            \?)	dna-echo -e "Invalid option | ${n-}-${OPTARG}${r-} | for function | ${n-}${FUNCNAME[0]}${r-} |."
                dna-exit
                ;;
            esac
    done
    OPTIND=1

    ############################################################################

    this_ipv4="$(dig +short myip.opendns.com @resolver1.opendns.com)"

    dna-echo -m "Your IPv4 public address appears to be: | ${y-}${this_ipv4}${n-} |."

    unset silent

}
