#!/usr/bin/env bash

dna-install_duplicity() {

	echo "${b-}Now installing the duplicity backup utility...${x-}"
	echo

	dna-get_distro_name

	if [ $distro_name = "Ubuntu" ]
	then
		dna-install_dependencies -p "software-properties-common"
		apt-add-repository ppa:duplicity-team/ppa -y
		echo
	fi

	dna-install_dependencies -p "libpcre3-dev duplicity python-pip s3cmd pwgen pv ufw curl" #review
	pip install --upgrade pip
	pip install boto || true
	pip install --upgrade boto
	echo

	echo "${b-}Finished installing duplicity.${x-}"
	echo

}
