#!/usr/bin/env bash

dna-install_easyengine() {

	operation_message="[re-]installing and updating EasyEngine..."

	dna-echo_operation -h

	wget -qO ee https://raw.githubusercontent.com/EasyEngine/easyengine/master/install
	bash ee || true
	rm ee
	source /etc/bash_completion.d/ee_auto.rc
	echo
	ee update || true
	echo
	rm /tmp/eeupdate* &> /dev/null || true
	mkdir -p /var/www/
	chown -R www-data:www-data /var/www/
	echo
	ufw allow 80 || true
	ufw allow 443 || true
	echo

	dna-echo_operation -t

}
