#!/usr/bin/env bash

dna-install_certbot() {

	dna-echo -m "Now installing certbot/letsencrypt..."

	dna-get_distro_name

	if [ $distro_name = "Ubuntu" ]
	then
		dna-install_dependencies -p "software-properties-common"
		apt-add-repository -yu ppa:certbot/certbot
		echo
	fi

	dna-install_dependencies -p "certbot"
	certbot &> /dev/null || true

	dna-echo -m "${g-}Finished installing certbot/letsencrypt."

}
