#!/usr/bin/env bash

dna-install_build_tools() {

    dna-install_dependencies -p "build-essential libpcre3-dev"

}

dna-install_certbot() {

	operation_message="installing certbot/letsencrypt"
	dna-echo_operation -h

	dna-get_distro_name

	if [ "${distro_name}" = "ubuntu" ]
	then

		dna-install_dependencies -p "software-properties-common"
		apt-add-repository -yu ppa:certbot/certbot
		echo
		dna-install_dependencies -p "certbot"

	elif [ "${distro_name}" = "debian" ]
	then

        dna-enable_debian_backports_repo
        apt-get update
		apt-get install certbot -t stretch-backports
		echo

	fi

	certbot &> /dev/null || true

	dna-echo_operation -t

}

dna-install_dependencies() {

    ############################################################################

    if [ $# -eq 0 ]
    then
        dna-echo -e "No argument supplied for function | ${r-}${FUNCNAME[0]}${n-} |."
        dna-exit
    fi

    while getopts ":ep:" arguments
    do
        case "${arguments}" in
            e)	allow_errors="y"
                ;;
            p)	packages="${OPTARG}"
                ;;
            \?)	dna-echo -e "Invalid option | ${n-}-$OPTARG${r-} | for function | ${n-}${FUNCNAME[0]}${r-} |."
                dna-exit
                ;;
        esac
    done
    OPTIND=1

    if [ -z "${packages-}" ]
    then
        dna-echo -e "Argument | ${n-}packages [-p]${r-} | must be supplied for function | ${n-}${FUNCNAME[0]}${r-} |."
        dna-exit
    fi

    ############################################################################

    operation_message="installing dependencies"

    dna-echo_operation -h

    dna-check_dpkg_availability

    dna-apt_update

    if ! apt-get -y install $packages                                           ### Do NOT escape this variable
    then

        echo

        if [ "${allow_errors-null}" = "y" ] || [ "${dna_global_allow_apt_errors-}" = "y" ]
        then

            dna-echo -e "An error occured performing APT operations."
            dna-echo -m "It is likely that by continuing the installation this and any other errors collected along the way will be naturally resolved."

            dna-ask_for_boolean -d "y" -q "Would you like to continue the installation anyway?"

            if [ "${boolean_output}" = "y" ]
            then
                dna-echo -n -m "Ok, continuing installation anyway..."
            else
                dna-echo -m "Ok, aborting..."
                dna-exit
            fi

        else

            dna-echo -e "An error occured performing APT operations."
            dna-exit

        fi

    fi

    echo

    set -e

    dna-echo_operation -t

    unset allow_errors
    unset packages

}

dna-install_duplicity() {

	operation_message="installing the duplicity backup utility"

	dna-echo_operation -h

	dna-get_distro_name

	if [ "${distro_name}" = "ubuntu" ]
	then
		dna-install_dependencies -p "software-properties-common"
		apt-add-repository ppa:duplicity-team/ppa -y
		echo
	fi

	dna-install_dependencies -p "libpcre3-dev duplicity python-pip s3cmd pwgen curl pv"
	pip install --upgrade pip
	/usr/local/bin/pip install boto
	/usr/local/bin/pip install --upgrade boto
	echo

	dna-echo_operation -t

}

dna-install_easyengine() {

	operation_message="[re-]installing and updating EasyEngine..."

	dna-echo_operation -h

	wget -qO ee https://raw.githubusercontent.com/EasyEngine/easyengine/master/install
	bash ee || true
	rm ee
	source /etc/bash_completion.d/ee_auto.rc
	echo
	ee update || true
	echo
	rm /tmp/eeupdate* &> /dev/null || true
	mkdir -p /var/www/
	chown -R www-data:www-data /var/www/
	echo
	ufw allow 80 || true
	ufw allow 443 || true
	echo

	dna-echo_operation -t

}

dna-install_mail_notifications() {

    while getopts ":f" arguments
    do
        case "${arguments}" in
            f)	force="y"
                ;;
            \?)	dna-echo -e "Invalid option | ${n-}-$OPTARG${r-} | for function | ${n-}${FUNCNAME[0]}${r-} |."
                dna-exit
                ;;
        esac
    done
    OPTIND=1

    hostname="$(cat /etc/hostname)"

    dna-get_distro_name

    install_mailutils() {

        ### [re-]Install mailutils

        debconf-set-selections <<< "postfix postfix/mailname string $hostname"
        debconf-set-selections <<< "postfix postfix/main_mailer_type string 'Internet Site'"

        if [ "${distro_name}" = "ubuntu" ]
    	then

            dna-install_dependencies -p "mailutils"

        elif [ "${distro_name}" = "debian" ]
        then

            dna-install_dependencies -p "mailutils postfix"

        fi

        ### Reload postfix

        /etc/init.d/postfix reload
        echo

    }

    install_mail_notifications_proceed() {

        operation_message="[purging and re-]installing the local mailserver"

        dna-echo_operation -h

        ### Purge any existing local server installation

        apt-get -y purge mailutils postfix || true

        echo

        install_mailutils

        dna-echo_operation -t

    }

    if [ "${force-}" = "y" ]
    then

        install_mail_notifications_proceed

    else

        dna-ask_for_boolean -d "y" -q "[Purge and re-]install the local mailserver for task notifications?"

        if [ "${boolean_output}" = "y" ]
        then

            dna-echo -m "Ok, proceeding..."

            install_mail_notifications_proceed

        else

            dna-echo -m "Ok, skipping."

    	fi

        unset boolean_output

    fi

    unset install_mailutils force

}

dna-install_mosh() {

    operation_message="installing Mosh"
    dna-echo_operation -h

    ############################################################################

    dna-get_distro_name

    if [ "${distro_name}" = "ubuntu" ]
    then
        dna-install_dependencies -p "software-properties-common"
        add-apt-repository -y ppa:keithw/mosh
        apt-get update
    fi

    ############################################################################

    dna-install_dependencies -p "mosh"

    ############################################################################

    if dpkg -s ufw &> /dev/null
    then
        ufw allow 60000:61000/udp
    else
        iptables -I INPUT 1 -p udp --dport 60000:61000 -j ACCEPT
    fi

    ############################################################################

    dna-echo_operation -t

}

dna-install_nginx() {

    operation_message="installing NGINX"
    dna-echo_operation -h

    dna-get_distro_name
    dna-get_distro_codename

    curl -O https://nginx.org/keys/nginx_signing.key && apt-key add ./nginx_signing.key
    rm ./nginx_signing.key
    echo "deb http://nginx.org/packages/${distro_name}/ ${distro_codename} nginx" > "/etc/apt/sources.list.d/nginx.list"
    echo "deb-src http://nginx.org/packages/${distro_name}/ ${distro_codename} nginx" >> "/etc/apt/sources.list.d/nginx.list"
    apt-get update
    echo

    dna-install_dependencies -p "nginx"

    dna-echo_operation -t

}

dna-localize_sslh_install() {

    ### Prepare the installation environment by reading the current system SSH port and fetching IP connectivity information

    dna-read_conf_settings

    dna-get_public_ipv4
    dna-check_ipv6_connectivity -s

    ### Localize install with this machine's info

    sed -i "s|ssh_port-var|${ssh_port}|g" "/etc/sslh.cfg"

	sed -i "s|public_ipv4-var|${public_ipv4}|g" "/etc/sslh.cfg"

    if [ "${ipv6_available}" = "y" ]
	then
		sed -i "s|#ipv6_comma|,|g" "/etc/sslh.cfg"
		sed -i "s|#ipv6_line||g" "/etc/sslh.cfg"
		sed -i "s|this_ipv6-var|${this_ipv6}|g" "/etc/sslh.cfg"
	else
		sed -i "s|#ipv6_comma||g" "/etc/sslh.cfg"
		sed -i "s|#ipv6_line|#|g" "/etc/sslh.cfg"
	fi

}

dna-install_sslh() {

	operation_message="installing SSLH"
    dna-echo_operation -h

    ############################################################################

    ### Abort installation if current SSH session is being carried out over SSLH itself

    dna-abort_on_sslh_session

    ############################################################################

    ### Install dependencies

	dna-install_build_tools
    dna-install_dependencies -e -p "libwrap0-dev libconfig-dev"

    ############################################################################

    ### Stop / kill if it's already installed and currently running

    if systemctl is-active --quiet sslh
    then
    	/usr/sbin/service sslh stop
    fi

    if pgrep sslh &> /dev/null ; then sudo killall sslh ; fi

    ############################################################################

    ### Clone

    if [ -d "${tmp_project_dir}/sslh" ]
    then
        rm -r "${tmp_project_dir}/sslh"
    fi

	git clone https://github.com/yrutschle/sslh "${tmp_project_dir}/sslh"

    ############################################################################

    ### Install

	( cd "${tmp_project_dir}/sslh" && git checkout v1.20 && make install && make && cp sslh-select /usr/local/sbin/sslh )

    ############################################################################

    ### Install default config files

    cat <<EOF >/etc/sslh.cfg
foreground: false;
inetd: false;
numeric: false;
transparent: false;
timeout: 2;
user: "nobody";
pidfile: "/var/run/sslh.pid";

syslog_facility: "auth";

listen:
(
    { host: "public_ipv4-var";       port: "443"; }#ipv6_comma
#ipv6_line    { host: "this_ipv6-var";       port: "443"; }
);

protocols:
(
    { name: "ssh";      host: "localhost";          port: "ssh_port-var";     keepalive: true; fork: true;                                },
    { name: "tls";      host: "localhost";          port: "443";    log_level: 0;                                               }
);

on-timeout: "timeout";
EOF

	cat <<EOF >/etc/init.d/sslh
#! /bin/sh

### BEGIN INIT INFO
# Provides:		sslh
# Required-Start:    \$remote_fs \$syslog
# Required-Stop:     \$remote_fs \$syslog
# Default-Start:	2 3 4 5
# Default-Stop:		1
# Short-Description:	sslh proxy ssl & ssh connections
### END INIT INFO

set -e
tag=sslh
facility=user.info

# /etc/init.d/sslh: start and stop the sslh proxy daemon

if test -f /etc/default/sslh; then
    . /etc/default/sslh
fi

# The prefix is normally filled by make install. If
# installing by hand, fill it in yourself!
PREFIX=/usr/local
DAEMON=\$PREFIX/sbin/sslh

start()
{
        echo "Start services: sslh"
        mkdir -p /var/run/sslh/
        touch /var/run/sslh/sslh.pid
        \$DAEMON -F/etc/sslh.cfg
        logger -t \${tag} -p \${facility} -i 'Started sslh'
}

stop()
{
        echo "Stop services: sslh"
	killall \$DAEMON
      	logger -t \${tag} -p \${facility} -i 'Stopped sslh'
}


case "\$1" in
	  start)
		    start
		    ;;
	  stop)
		    stop
		    ;;
    restart)
		    stop
		    sleep 5
		    start
		    ;;
	  *)
		    echo "Usage: /etc/init.d/sslh {start|stop|restart}" >&2
		    ;;
esac

exit 0
EOF

    ############################################################################

    dna-localize_sslh_install

    ############################################################################

    ### Finish

	chmod +x "/etc/init.d/sslh"

	update-rc.d sslh defaults

	systemctl daemon-reload

	rm -r "${tmp_project_dir}/sslh"

	mkdir -p /var/run/sslh
	touch /var/run/sslh/sslh.pid

    ############################################################################

    ### Activate

	/usr/sbin/service sslh restart || true

	echo

	dna-echo_operation -t

}
