#!/usr/bin/env bash

dna-install_mail_notifications() {

    hostname="$(cat /etc/hostname)"

    dna-get_distro_name

    install_mailutils() {

        ### [re-]Install mailutils

        debconf-set-selections <<< "postfix postfix/mailname string $hostname"
        debconf-set-selections <<< "postfix postfix/main_mailer_type string 'Internet Site'"

        if [ "${distro_name}" = "Ubuntu" ]
    	then

            dna-install_dependencies -p "mailutils"

        elif [ "${distro_name}" = "Debian" ]
        then

            dna-install_dependencies -p "mailutils postfix"

        fi

        ### Reload postfix

        /etc/init.d/postfix reload
        echo

    }

    dna-ask_for_boolean -d "y" -q "[Purge and re-]install the local mailserver for task notifications?"

    if [ "${boolean_output}" = "y" ]
    then

        dna-echo -m "Ok, proceeding..."

        operation_message="[purging and re-]installing the local mailserver"

        dna-echo_operation -h

        ### Purge any existing local server installation

        apt-get -y purge mailutils postfix || true

        install_mailutils

        dna-echo_operation -t

    else

        dna-echo -m "Ok, skipping."

	fi

    unset boolean_output install_mailutils

}
