#!/usr/bin/env bash

dna-install_dependencies() {

    if [ $# -eq 0 ]
    then
        echo "${r-}${b-}No argument supplied for function | ${FUNCNAME[0]} |.${x-}"
        echo
        dna-exit
    fi

    while getopts ":ep:" arguments; do
        case $arguments in
            e)	allow_errors="y"
            ;;
            p)	packages="$OPTARG"
            ;;
            \?)	echo "${r-}${b-}Invalid option | -$OPTARG | for function | ${FUNCNAME[0]} |.${x-}"
            echo
            dna-exit
            ;;
        esac
    done
    OPTIND=1

    if [ -z "${packages-}" ]
    then
        echo "${r-}${b-}Packages [option | -p |] must be supplied for function | ${FUNCNAME[0]} |.${x-}"
        echo
        dna-exit
    fi

    echo "${b-}Now installing dependencies...${x-}"
    echo

    dna-apt_update
    if ! apt-get -y install $packages
    then
        if [ "${allow_errors-null}" = "y" ]
        then
            echo
            echo "${r-}${b-}An error occured performing APT operations.${x-}"
            echo
            echo "${b-}If this is an upgrade [rather than a first install] it is possible that by continuing the installation this and any other errors collected along the way will be fixed automatically.${x-}"
            echo
            ask_for_boolean_question="Would you like to continue the installation anyway?"
            dna-ask_for_boolean_def_no
            if [ "$ask_for_boolean_output" = "n" ]
            then
                dna-exit
            else
                echo "${b-}Ok, continuing installation anyway...${x-}"
            fi
        else
            echo
            echo "${r-}${b-}An error occured performing APT operations.${x-}"
            echo
            dna-exit
        fi
    fi

    echo

    set -e

    echo "${g-}${b-}Finished installing dependencies.${x-}"
    echo

    unset allow_errors
    unset packages

}
