#!/usr/bin/env bash

dna-install_dependencies() {

    ############################################################################

    if [ $# -eq 0 ]
    then
        dna-echo -e "No argument supplied for function | ${r-}${FUNCNAME[0]}${n-} |."
        dna-exit
    fi

    while getopts ":ep:" arguments
    do
        case "${arguments}" in
            e)	allow_errors="y"
                ;;
            p)	packages="${OPTARG}"
                ;;
            \?)	dna-echo -e "Invalid option | ${n-}-$OPTARG${r-} | for function | ${n-}${FUNCNAME[0]}${r-} |."
                dna-exit
                ;;
        esac
    done
    OPTIND=1

    if [ -z "${packages-}" ]
    then
        dna-echo -e "Argument | ${n-}packages [-p]${r-} | must be supplied for function | ${n-}${FUNCNAME[0]}${r-} |."
        dna-exit
    fi

    ############################################################################

    operation_message="installing dependencies"

    dna-echo_operation -h

    dna-check_dpkg_availability

    dna-apt_update

    if ! apt-get -y install "${packages}"
    then

        echo

        if [ "${allow_errors-null}" = "y" ]
        then

            dna-echo -e "An error occured performing APT operations."
            dna-echo -m "If this is an upgrade [rather than a first install] it is possible that by continuing the installation this and any other errors collected along the way will be naturally resolved."

            dna-ask_for_boolean -d "n" -q "Would you like to continue the installation anyway?"

            if [ "$boolean_output" = "y" ]
            then
                dna-echo -m "Ok, continuing installation anyway..."
            else
                dna-echo -m "Ok, aborting..."
                dna-exit
            fi

        else

            dna-echo -e "An error occured performing APT operations."
            dna-exit

        fi

    fi

    echo

    set -e

    dna-echo_operation -t

    unset allow_errors
    unset packages

}
