#!/bin/bash

os-install_dependencies() {

    if [ $# -eq 0 ]
    then
        echo "${r}${b}No argument supplied for function | ${FUNCNAME[0]} |.${x}"
        echo
        os-exit_function
    fi

    while getopts ":ep:" arguments; do
        case $arguments in
            e)	allow_errors="y"
            ;;
            p)	packages="$OPTARG"
            ;;
            \?)	echo "${r}${b}Invalid option | -$OPTARG | for function | ${FUNCNAME[0]} |.${x}"
            echo
            os-exit_function
            ;;
        esac
    done
    OPTIND=1

    echo "${b}Now installing dependencies...${x}"
    echo

    if [ "${allow_errors-null}" = "y" ]
    then
        set +e
    fi

    apt-get update
    if ! apt-get -y install "$packages"
    then
        echo "${r}${b}An error occured performing APT operations.${x}"
        echo
        echo "${b}It is possible that by continuing the installation this and any other errors collected along the way will correct themselves automatically.${x}"
        echo
        ask_for_boolean_question="Would you like to continue the installation anyway?"
        os-ask_for_boolean_def_no
        if [ "$ask_for_boolean_output" = "n" ]
        then
            os-exit_function
        else
            echo "${b}Ok, continuing installation anyway...${x}"
            echo
        fi
    fi

    echo

    set -e

    echo "${b}Finished installing dependencies.${x}"
    echo

    unset allow_errors
    unset packages

}
