#!/usr/bin/env bash

dna-link_tools() {

    (
            cd "${tools_dir}"

            for tool_script in "${proj_name}"-*
            do

                chmod +x "${tool_script}"

                    if [ ! -f "/usr/local/bin/${tool_script}" ]
                    then
                            ln -s "${tools_dir}/${tool_script}" "/usr/local/bin/"
                    fi

            done
    )

}
