#!/bin/bash

os-log_script() {

	# All in One Bash Logger | v0.52 | 20171018 | 20171225 | Nk

	scriptname=$(basename "$0")                                                 # The name of this script
	now="$(date +"%Y-%m-%d_%H-%M-%S")"                                          # The current timestamp
	logdir="$HOME/logs/$scriptname"                                             # Don't store anything else than logs in here!
	logfile="$logdir/$now"                                                      # The new logfile
	if [[ -t 1 ]]; then interactive=y; else interactive=n; fi                   # Determine if this is an interactive shell
	if [ $interactive = "n" ]                                                   # If non-interactive, then...
	then
		mkdir -p "$logdir"                                                      # Touch the logdir
		touch "$logfile"                                                        # Touch the logfile
		if [ -f "$logdir"/latest-log ]; then rm "$logdir"/latest-log; fi        # Remove the old latest-log symlink
		ln -s "$logfile" "$logdir"/latest-log                                   # Recreate the latest-log symlink
		( cd "$logdir" && rm "$(ls -t | awk 'NR>43')" ) 2> /dev/null || true    # Delete all logs older than the newest 42
		exec >  >(tee -ia "$logfile")                                           # Log stdout to logfile
		exec 2> >(tee -ia "$logfile" >&2)										# Log stderr to logfile
	fi
	echo "Starting $scriptname script on $now..." && echo                       # Write heading to logfile
	chmod -R 700 "$logdir"                                                      # Secure logs directory

}

os-head_script() {

	scriptname=$(basename "$0")                                                 # The name of this script
	now="$(date +"%Y-%m-%d_%H-%M-%S")"                                          # The current timestamp
	echo "Starting $scriptname script on $now..." && echo                       # Write heading to logfile

}
