#!/bin/bash

os-log_script() {

	### All in One Bash Logger | v0.6.0 | 2017-10-18 | 2018-05-25 | Nz

	script_name=$(basename "$0")												### The name of this script
	now="$(date +"%Y-%m-%d_%H-%M-%S")"											### The current timestamp
	log_dir="$HOME/logs/$script_name"											### Don't store anything else than logs in here!
	log_file="$log_dir/$now"													### The new log_file
	if [[ -t 1 ]]; then interactive=y; else interactive=n; fi					### Determine if this is an interactive shell
	if [ $interactive = "n" ]													### If non-interactive, then...
	then
		mkdir -p "$log_dir"														### Touch the log_dir
		touch "$log_file"														### Touch the log_file
		if [ -f "$log_dir"/latest-log ]; then rm "$log_dir"/latest-log; fi		### Remove the old latest-log symlink
		ln -s "$log_file" "$log_dir"/latest-log									### Recreate the latest-log symlink
		( cd "$log_dir" && rm "$(ls -t | awk 'NR>43')" ) 2> /dev/null || true	### Delete all logs older than the newest 42
		exec >  >(tee -ia "$log_file")											### Log stdout to log_file
		exec 2> >(tee -ia "$log_file" >&2)										### Log stderr to log_file
	fi
	echo "Starting $script_name script on $now..." && echo						### Write heading to log_file
	chmod -R 700 "$log_dir"														### Secure logs directory

}

os-head_script() {

	script_name=$(basename "$0")												### The name of this script
	now="$(date +"%Y-%m-%d_%H-%M-%S")"											### The current timestamp
	echo "Starting $script_name script on $now..." && echo						### Write heading to log_file

}
