#!/usr/bin/env bash

dna-set_admin_email() {

	describe_setting() {

		echo "${b-}$proj_name sends you email notifications for any scheduled job runtime errors and / or failures.${x-}"
		echo

	}

	dna-set_option -o admin_mail -v n -d y
}
