#!/usr/bin/env bash

dna-touch_tmp_project_dir() {

	mkdir -p "${tmp_project_dir}"

}

dna-remove_tmp_project_dir() {

	if [ -d "${tmp_project_dir}" ]
	then
		rm -r "${tmp_project_dir}"
	fi

}

dna-refresh_tmp_project_dir() {

	dna-remove_tmp_project_dir
	dna-touch_tmp_project_dir

}
