#!/usr/bin/env bash

set -eu

dna-tor_get_hidden_service_hostname() {

    if [ -f "/var/lib/tor/hidden_service/hostname" ]
	then

        tor_hs_hostname="$(cat "/var/lib/tor/hidden_service/hostname")"

        dna-set_option -o "tor_hidden_service_hostname" -t g -p "tor" -s "${tor_hs_hostname}"

        dna-echo -m "Your publicly reachable | ${o-}.onion hostname${n-} | is: | ${y-}${tor_hs_hostname}${n-} |."

        dna-press_to_continue

    else

        dna-echo -e "Tor hidden service is not enabled on this machine."

    fi

}

dna-tor_enable_hidden_service() {

    ############################################################################

    ### Enable Tor hidden service

    if grep -q "^HiddenServiceDir /var/lib/tor/hidden_service/$" "/etc/tor/torrc"
    then

        dna-echo -m "Tor hidden service is already enabled on this machine."

    elif grep -q "^#HiddenServiceDir /var/lib/tor/hidden_service/$" "/etc/tor/torrc"
    then

        dna-echo -m "Tor hidden service is disabled on this machine. Enabling it now..."

        sed -i "s|#HiddenServiceDir /var/lib/tor/hidden_service/|HiddenServiceDir /var/lib/tor/hidden_service/|g" "/etc/tor/torrc"

        /usr/sbin/service tor restart

    else

        dna-echo -m "Tor hidden service directive not present. Creating and enabling it now..."

        sed -i "/############### This section is just for location-hidden services ###/a HiddenServiceDir /var/lib/tor/hidden_service/" "/etc/tor/torrc"

        /usr/sbin/service tor restart

    fi

    dna-wait -s "4" -d "Now allowing tor to start up correctly..."

    ############################################################################

    ### Check hidden service creation

    if [ -f "/var/lib/tor/hidden_service/hostname" ]
	then

        dna-echo -s "Tor hidden service was enabled successfully."

        dna-tor_get_hidden_service_hostname

    else

        dna-echo -e "Tor hidden service was NOT enabled successfully."

    fi

    ############################################################################

}

dna-tor_disable_hidden_service() {

    if ! grep -q "^HiddenServiceDir /var/lib/tor/hidden_service/$" "/etc/tor/torrc"
    then

        dna-echo -m "Tor hidden service is already disabled on this machine."

    else

        dna-echo -m "Tor hidden service is currently enabled on this machine. Disabling it now..."

        sed -i "s|HiddenServiceDir /var/lib/tor/hidden_service/|#HiddenServiceDir /var/lib/tor/hidden_service/|g" "/etc/tor/torrc"

        /usr/sbin/service tor restart

        dna-echo -m "Tor hidden service was disabled successfully."

    fi

}
