#!/usr/bin/env bash

set -eu

dna-get_dna_version() {

    dna-echo -m "dna version: | ${l-}$(cat ${dna_version_file_path})${n-} |."

}

dna-get_project_version() {

    dna-echo -m "${project_name} version ${y-}initiated${n-}: | ${l-}${version_initiated}${n-} |."
    dna-echo -m "${project_name} version ${o-}installed${n-}: | ${l-}${version_installed}${n-} |."

}
