#!/bin/bash

os-ask_for_boolean_def_yes() {

    unset ask_for_boolean_output
    read -p "${b-}${ask_for_boolean_question} (Y/n): ${x-}" -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Nn]$ ]]
    then
        ask_for_boolean_output=y
    else
        echo
        ask_for_boolean_output=n
    fi
    unset ask_for_boolean_question

}

os-ask_for_boolean_def_no() {

    unset ask_for_boolean_output
    read -p "${b-}${ask_for_boolean_question} (y/N): ${x-}" -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]
    then
        echo
        ask_for_boolean_output=y
    else
        ask_for_boolean_output=n
    fi
    unset ask_for_boolean_question

}
