#!/bin/bash

os-check_var_defined() {

        os-check_argument_presence

        if [ ! -z "${1-}" ]
        then
                var_defined=y
        else
                var_defined=n
        fi

}
