#!/bin/bash

os-check_distro_ubuntu16() {

    # Check distro

    current_ubuntu_version="$(lsb_release -rs)"

    if [ "$current_ubuntu_version" != "16.04" ]
    then
        if [ "$current_ubuntu_version" = "17.10" ] || [ "$current_ubuntu_version" = "18.04" ]
        then
            read -p "${b}Ubuntu 17.10 / 18.04 detected. Proceed in testing mode? [things could break] (Y/n): ${x}" -n 1 -r
            echo
            if [[ ! $REPLY =~ ^[Nn]$ ]]
            then
                echo "${b}Ok, continuing anyway...${x}"
                echo
            else
                echo
                os-exit_function
            fi
        else
            echo "${r}${b}$short_name only runs on Ubuntu 16.04. You are running:${x}"
            echo
            lsb_release -d | sed 's/.*:\s*//'
            echo
            os-exit_function
        fi
    fi

}
