#!/bin/bash

os-check_distro_ubuntu16() {

    # Check distro

    if [ "$(lsb_release -d | sed 's/.*:\s*//' | sed 's/16\.04\.[0-9]/16.04/')" != "Ubuntu 16.04 LTS" ]
    then
        if [ "$(lsb_release -d | sed 's/.*:\s*//' | sed 's/17\.04\.[0-9]/17.10/')" = "Ubuntu 17.10" ]
        then
            read -p "${b}Ubuntu 17.10 detected. Proceed in testing mode? [things could break] (Y/n): ${x}" -n 1 -r
            echo
            if [[ ! $REPLY =~ ^[Nn]$ ]]
            then
                echo "${b}Ok, continuing anyway...${x}"
                echo
            else
                echo
                os-exit_function
            fi
        else
            echo "${r}${b}$short_name only runs on Ubuntu 16.04. You are running:${x}"
            echo
            lsb_release -d | sed 's/.*:\s*//'
            echo
            os-exit_function
        fi
    fi

}
