#!/bin/bash

os-check_argument_presence() {

        if [ $# -eq 0 ]
        then
                echo "${r}${b}No argument supplied.${x}"
                echo
                echo "${b}Exiting...${x}"
                echo
                exit 1
        fi

}
