#!/bin/bash

os-install_dependencies() {

    if [ $# -eq 0 ]
    then
        echo "${r}${b}No argument supplied for function | ${FUNCNAME[0]} |.${x}"
        echo
        os-exit_function
    fi

    while getopts ":ep:" arguments; do
        case $arguments in
            e)	allow_errors="y"
            ;;
            p)	packages="$OPTARG"
            ;;
            \?)	echo "${r}${b}Invalid option | -$OPTARG | for function | ${FUNCNAME[0]} |.${x}"
            echo
            os-exit_function
            ;;
        esac
    done

    echo "${b}Now installing dependencies...${x}"
    echo

    if [ "${allow_errors-null}" = "y" ]
    then
        set +e
    fi

    apt-get update
    apt-get -y install "$packages"

    echo

    set -e

    echo "${b}Finished installing dependencies.${x}"
    echo

    OPTIND=1

}
