#!/bin/bash

os-install_dependencies() {

        if [ $# -eq 0 ]
        then
                echo "${r}${b}No argument supplied for function | ${FUNCNAME[0]} |.${x}"
                echo
                os-exit_function
        fi

        echo "${b}Now installing dependencies...${x}"
        echo
        apt-get update
        apt-get -y install "$1"
        echo
        echo "${b}Finished installing dependencies.${x}"
        echo

}
