#!/bin/bash

os-set_option() {

	########################################################################

	while getopts ":o:v:d:" arguments; do
		case $arguments in
			o)	option="$OPTARG"
				;;
			v)	validate="$OPTARG"
				;;
			d)	describe="$OPTARG"
				;;
			\?)	echo "${r}${b}Invalid option | -$OPTARG | for function | ${FUNCNAME[0]} |.${x}"
				echo
				os-exit_function
				;;
		esac
	done

	if [ -z "${option-}" ]
	then
		echo "${r}${b}Argument | option [-o] | must be supplied for function | ${FUNCNAME[0]} |.${x}"
		echo
		os-exit_function
	fi

	if [ ! -z "${validate-}" ]
	then
		case $validate in
			y)	validate_input=y
				;;
			n)	validate_input=n
				;;
			*)	echo "${r}${b}Invalid content for validate argument in function | ${FUNCNAME[0]} |.${x}"
				echo
				os-exit_function
				;;
		esac
	fi

	if [ ! -z "${describe-}" ]
	then
		case $describe in
			y)	describe_setting=y
				;;
			n)	describe_setting=n
				;;
			*)	echo "${r}${b}Invalid content for describe argument in function | ${FUNCNAME[0]} |.${x}"
				echo
				os-exit_function
				;;
		esac
	fi

	########################################################################

	opt_path="$conf_dir/$option"

	if [ -f "$opt_path" ]
	then
		prev_val="$(cat $opt_path)"

		if [ "${validate_input-}" = "y" ]
		then

			### validate_option must be defined immediately prior to calling this function.

			validate_option

		else

			valid=y

		fi

	else

		touch $opt_path
		valid=n

	fi

	if [ $valid = "y" ]
	then
		echo "${b}Your previous value for option | ${g}$option${x}${b} | was: | ${g}$prev_val${x}${b} |. ${x}"
		echo
		read -rp "${b}Is this still correct? (Y/n): ${x}" -n 1
		echo
		if [[ ! $REPLY =~ ^[Nn]$ ]]
		then
			echo "${b}Ok, keeping | $prev_val | as your value for option | $option |.${x}"
			echo
			value="$prev_val"
		else
			echo
			skip_descr=y
		fi
	fi

	if [ -z "${value-}" ]
	then

		defined=n
		until [ $defined = "y" ]
		do
			new_val=""
			until [ ! $new_val = "" ]
			do
				if [ "${skip_descr-}" = "y" ]
				then
					read -rp "${b}Now specify your new value for option | $option |: ${x}" new_val
					echo
				else
					if [ "${describe_setting-}" = "y" ]
					then
						### describe_setting must be defined immediately prior to calling this function.

						describe_setting

						echo
					fi
					read -rp "${b}Now specify your value for option | $option |: ${x}" new_val
					echo
				fi
			done
			valid=n
			until [ $valid = "y" ]
			do
				read -n 1 -rp "${b}Is | $new_val | correct? (Y/n/e[xit]) ${x}" answer;
				case $answer in
				"")
					echo
					valid=y
					defined=y
					;;
				y)
					echo -e "\\n"
					valid=y
					defined=y
					;;
				n)
					echo -e "\\n"
					echo "${b}Ok, then please try again...${x}"
					echo
					valid=y
					defined=n
					;;
				e)
					echo -e "\\n"
					echo "${b}Exiting...${x}"
					echo
					exit
					;;
				*)
					echo -e "\\n"
					echo "${r}${b}Invalid option. Retry...${x}"
					echo
					valid=n
					defined=n
					;;
				esac
			done
		done
		echo "$new_val" > "$opt_path"
		echo "${b}Option | $option | set to value | $new_val |. ${x}"
		echo
		value="$(cat $opt_path)"

	fi
	clear

}
